use  group_by ;

CREATE TABLE sales_data (
    sale_id INT,
    product_name VARCHAR(50),
    category VARCHAR(30),
    customer_id INT,
    quantity INT,
    price_per_unit DECIMAL(10,2),
    sale_date DATE
);

INSERT INTO sales_data VALUES
(1, 'Laptop', 'Electronics', 101, 1, 800.00, '2025-07-01'),
(2, 'Headphones', 'Electronics', 102, 2, 50.00, '2025-07-02'),
(3, 'Desk', 'Furniture', 103, 1, 150.00, '2025-07-03'),
(4, 'Chair', 'Furniture', 101, 4, 75.00, '2025-07-01'),
(5, 'Monitor', 'Electronics', 104, 2, 200.00, '2025-07-04'),
(6, 'Keyboard', 'Electronics', 105, 1, 45.00, '2025-07-05'),
(7, 'Mouse', 'Electronics', 106, 3, 25.00, '2025-07-06'),
(8, 'Printer', 'Electronics', 107, 1, 120.00, '2025-07-07'),
(9, 'Bookshelf', 'Furniture', 108, 2, 80.00, '2025-07-08'),
(10, 'Lamp', 'Furniture', 103, 3, 30.00, '2025-07-01'),
(11, 'Notebook', 'Stationery', 102, 5, 5.00, '2025-07-01'),
(12, 'Pen', 'Stationery', 102, 10, 1.50, '2025-07-02'),
(13, 'Tablet', 'Electronics', 109, 1, 400.00, '2025-07-03'),
(14, 'Webcam', 'Electronics', 110, 2, 70.00, '2025-07-04'),
(15, 'Whiteboard', 'Furniture', 101, 1, 90.00, '2025-07-05'),
(16, 'Stapler', 'Stationery', 111, 4, 6.00, '2025-07-06'),
(17, 'Chair', 'Furniture', 101, 2, 75.00, '2025-07-07'),
(18, 'Laptop', 'Electronics', 101, 1, 850.00, '2025-07-08'),
(19, 'Mousepad', 'Electronics', 105, 3, 10.00, '2025-07-08'),
(20, 'Notebook', 'Stationery', 102, 6, 5.00, '2025-07-08');

select * from sales_data;
--  Total quantity sold for each product
select Product_name ,sum(quantity) as total_Quantity 
from sales_data
group by Product_name 
order by Total_Quantity Desc ;

--  Total revenue generated by each category
select category , sum(price_per_unit * Quantity) as total_Revenue 
from sales_data
group by category
order by total_Revenue desc;

--  Total quantity purchased by each customer
select customer_id , sum(Quantity) as Cust_total_Quantity
from sales_data
group by customer_id order by cust_total_quantity desc ;

--   Number of transactions per sale date
select sale_date,
count(quantity) as transactions_per_date
 from sales_data 
 group by sale_date; 

--  Average quantity per product
select product_name, 
avg(quantity) as avg_quantity 
from sales_data 
group by product_name;

-- Total revenue per customer
select customer_id, 
sum(price_per_unit*quantity) as revenue 
from sales_data 
group by customer_id;

--  Total items sold on each day
select sale_date, 
sum(quantity) as item_sold 
from sales_data 
group by sale_date;

--  Count of different products sold in each category
select category, 
count(product_name) as product_sold_per_category 
from sales_data 
group by category;

--  List customers who bought more than 5 items in total
select customer_id, 
sum(Quantity) as item_purchased 
from sales_data 
group by customer_id 
having item_purchased>5; 


--  Find products that were sold more than 2 times
select product_name, 
sum(quantity) from sales_data 
group by product_name 
having sum(quantity)>2; 

--  Get sale dates where more than 3 transactions occurred
select sale_date, 
count(Quantity) as count_transaction 
from sales_data 
group by sale_date 
having count(Quantity)>3;

 