use group_by;
CREATE TABLE Sales (
    OrderID INT PRIMARY KEY,
    CustomerName VARCHAR(50),
    ProductName VARCHAR(50),
    Category VARCHAR(30),
    Quantity INT,
    UnitPrice DECIMAL(10,2),
    SalesAmount DECIMAL(10,2),
    SalesDate DATE,
    City VARCHAR(50),
    SalesPerson VARCHAR(50)
);

INSERT INTO Sales VALUES
(1,'Amit','Laptop','Electronics',2,50000,100000,'2025-01-05','Mumbai','Rahul'),
(2,'Priya','Mobile','Electronics',3,20000,60000,'2025-01-07','Pune','Sneha'),
(3,'Rohit','Tablet','Electronics',1,30000,30000,'2025-01-10','Delhi','Rahul'),
(4,'Neha','Chair','Furniture',5,3000,15000,'2025-01-12','Mumbai','Amit'),
(5,'Karan','Table','Furniture',2,7000,14000,'2025-01-15','Pune','Sneha'),
(6,'Pooja','Sofa','Furniture',1,25000,25000,'2025-01-18','Delhi','Rahul'),
(7,'Vikas','Printer','Electronics',2,12000,24000,'2025-01-20','Mumbai','Amit'),
(8,'Anjali','Laptop','Electronics',1,55000,55000,'2025-01-22','Pune','Sneha'),
(9,'Raj','Mobile','Electronics',4,18000,72000,'2025-01-25','Delhi','Rahul'),
(10,'Meena','Chair','Furniture',3,3500,10500,'2025-01-27','Mumbai','Amit'),
(11,'Arjun','Table','Furniture',2,8000,16000,'2025-02-01','Pune','Sneha'),
(12,'Sonia','Laptop','Electronics',1,60000,60000,'2025-02-03','Delhi','Rahul'),
(13,'Deepak','Mobile','Electronics',2,22000,44000,'2025-02-05','Mumbai','Amit'),
(14,'Rani','Printer','Electronics',3,11000,33000,'2025-02-08','Pune','Sneha'),
(15,'Nitin','Sofa','Furniture',1,28000,28000,'2025-02-10','Delhi','Rahul'),
(16,'Kavita','Tablet','Electronics',2,32000,64000,'2025-02-12','Mumbai','Amit'),
(17,'Ajay','Laptop','Electronics',1,58000,58000,'2025-02-15','Pune','Sneha'),
(18,'Payal','Chair','Furniture',4,3200,12800,'2025-02-18','Delhi','Rahul'),
(19,'Mohit','Mobile','Electronics',3,21000,63000,'2025-02-20','Mumbai','Amit'),
(20,'Komal','Table','Furniture',1,7500,7500,'2025-02-22','Pune','Sneha'),
(21,'Sachin','Laptop','Electronics',2,52000,104000,'2025-02-24','Delhi','Rahul'),
(22,'Asha','Printer','Electronics',1,13000,13000,'2025-02-26','Mumbai','Amit'),
(23,'Manoj','Sofa','Furniture',1,30000,30000,'2025-02-27','Pune','Sneha'),
(24,'Rekha','Mobile','Electronics',2,23000,46000,'2025-02-28','Delhi','Rahul'),
(25,'Vijay','Chair','Furniture',6,3000,18000,'2025-03-01','Mumbai','Amit');

select * from sales;

-- Q1. Find the total revenue generated by each product category.
select ProductName, sum(SalesAmount) as revenue_per_category from sales group by ProductName;

-- Q2. Display the total sales amount for each city.
select city, sum(salesamount) as total_sale_per_city from sales group by city;

-- Q3. Find the total quantity sold for each product.
select productname,
sum(Quantity) as Quantity_sold 
from sales group by productname;

select * from sales;
-- Q4. Show the average sales amount generated by each salesperson.

select salesperson,
avg(salesamount) average_sale_by_employee
from sales 
group by salesperson;
-- Q5. The management wants to identify high-performing categories.
-- Find categories whose total revenue is greater than 200000.
select category, 
sum(SalesAmount) as revenue 
from sales 
group by category 
having revenue>200000;

-- Q6. Find cities where the total sales amount exceeds 150000.
select * from sales;
select city, sum(SalesAmount) as total_sales_amount from sales group by city having total_sales_amount>150000;

-- Q7. The company wants to reward top salespersons.
-- Find salespersons who have generated revenue greater than 250000.
select SalesPerson , sum(SalesAmount) from sales group by SalesPerson having sum(SalesAmount)>250000;

-- Q8. Find products whose total quantity sold is more than 5 units.
select productname,
sum(quantity) as total_quantity
from sales
group by productname 
having total_quantity>5;

-- Q9. Display categories having an average sales amount greater than 40000.
select category,
avg(salesamount) as average_sales_category 
from sales 
group by category
having average_sales_category>40000;

-- Q10. Categorize each order using CASE:
-- SalesAmount >= 50000  -> 'High Sales'
-- SalesAmount between 20000 and 49999 -> 'Medium Sales'
-- Otherwise -> 'Low Sales'
select *,
case
when salesamount>=50000 then "High Class"
when salesamount between 20000 and 49999 then "Medium Class"
else "Low Sales"
end as order_category
from sales;

-- Q11. Create a CASE statement to classify products:
-- Electronics -> 'Tech Product'
-- Furniture -> 'Home Product'
select *,
case
when category="electronics" then "Tech Product"
else "Home Product"
end as Product_type
from sales;

-- Q12. Create a CASE statement to classify customers:
-- SalesAmount > 70000 -> 'Premium Customer'
-- SalesAmount between 30000 and 70000 -> 'Regular Customer'
-- Otherwise -> 'Basic Customer'
select *,
case
when SalesAmount>70000 then "Premium Customer"
when SalesAmount between 30000 and 70000 then "Regular Customer"
else "Basic Customer"
end as Customer_Tiers
from sales;

-- Q13. Find all customers whose names start with the letter 'A'.
select * from sales where CustomerName like "A%";

-- Q14. Find all products whose name contains the word 'top'.
select * from sales where productname like "%top%";

-- Q15. Find all salespersons whose names end with the letter 'a'.
select * from sales where SalesPerson like "%a";

-- 16. Find customers whose SalesAmount is greater than the average SalesAmount.
select * from sales where salesamount>(
select avg(salesamount)
from sales 
) order by salesamount asc;

-- 17. Find the order(s) with the highest SalesAmount.
select * from sales where SalesAmount=(
select max(salesamount)
from sales
);

-- 18. Find customers who purchased products from the 'Electronics' category.
select * from sales where category="electronics";

-- 19. Find sales records where UnitPrice is higher than the average UnitPrice of all products.
select * from sales where unitprice>(
select avg(unitprice) 
from sales
);

-- 20. Find products whose total sales amount is greater than the total sales amount of 'Printer'.
select productname, sum(salesamount) from sales group by productname having sum(salesamount)>(
select sum(salesamount) from sales where productname="printer"
);

-- 21. Find customers who purchased the most expensive product(s).
select * from sales where Unitprice=(
select max(UnitPrice) from sales);